language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - python setup.py install
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=random_words setup.py test
after_success:
    - coveralls
sudo: false
